### ISSUE TITLE
Problem with accented characters

### ISSUE THREAD

**Issue by thesoftwarebin** [eschulte/org-ehtml#21]
Hello, here's a recipe to reproduce my problem.

1) create this example file `index.org` and put it in your ehtml docroot:

```
# -*- coding: utf-8 -*-

#+TITLE: mytitle
#+HTML_EDITABLE_HEADLINES: t
#+HTML_EVERYTHING_EDITABLE: t

* myheader                                                         :EDITABLE:

mytext... citta.
```

2) enable the server with `(progn (require 'org-ehtml) (ws-start org-ehtml-handler 1000))`

3) open your browser and go to `http://localhost:10000`

4) hover the text `mytext... citta.`, click the `EDIT` button at the right side, change `citta` into `città` (it's the Italian "accented a" letter, Unicode `U+00E0`, UTF-8 encoding `c3 a0`), click "Save"

5) now look at your Emacs, you will see that a message appears: `utf-8-dos cannot encode these: \303 \240`, and Emacs prompts for you to amend the "wrong" chars or to select another charset.

Prompt at point 5) is undesired behaviour. And even if I choose a charset (utf-8, iso-8859-1 etc.) then I still get in `\303 \240` in `index.org` instead of `à`.

My workaround: I get a correct behaviour if (before performing point 4) I visit `index.org` and type `M-x toggle-enable-multibyte-characters RET` (i.e. change multibyte from enabled to disabled) and keep that buffer open.

Is this reproducible for you too? Any idea of what could be wrong?

Thanks, kindest regards.

Andrea

**Comment by TobiasZawada** [comment]
FYI: I've got the same problem with German umlauts.

**Comment by TobiasZawada** [comment]
@thesoftwarebin Could you update and test whether your problem is really solved?

**Comment by TobiasZawada** [comment]
@eschulte Maybe, @thesoftwarebin will never answer here. At least the problem with Umlauts is fixed.
