### ISSUE TITLE
enhancement: allow overriding css file

### ISSUE THREAD

**Issue by map7** [eschulte/org-ehtml#30]
Currently the styling is ox-ehtml.css and the only way to override to my understanding is to edit the ox-ehtml.css directly. It would be nice to have a variable which would allow an override of the CSS. 

Are you open to this idea?

**Comment by map7** [comment]
https://github.com/eschulte/org-ehtml/pull/31

**Comment by eschulte** [comment]
Yeah, makes sense, just merged that PR.
